# Generated by Django 5.2.6 on 2025-09-10 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        ('veterinarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('atendida', 'Atendida'), ('no_asiste', 'No se presentó'), ('cancelada', 'Cancelada')], default='reservada', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='veterinarios.veterinario')),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['-inicio'],
            },
        ),
    ]
